$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
    center: true,
    loop:false,
    margin:10,
    nav:true,
    autoplay:true,
    autoplayTimeout:3000,
    autoplayHoverPause:true,
    responsive:{
      0:{
        items:1
      },
      600:{
        items:1
      },
      1000:{
        items:2
      }
  }
  })
});